/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function openPackFiles(paths: Array<string>, useLazyLoading: boolean, ignoreMods: boolean, lockPackfile: boolean): PackFileHolder
export class PackFileHolder {
  getAllLuaFilePaths(): Array<string>
  getTextFile(filepath: string): string
}
